### ISSUE TITLE
User is not able to login with Virtual Assistant account.

### ISSUE THREAD

**Issue by vishavsoftiatric** [chameleonmode/chameleon.app-community#59]
**Description**: When the user login with the there Virtual Assistant account, then "Error Logging In - Response status code does not indicate success: 401 (Unauthorized).' error is getting displayinig.

**Bug Screenshot**: https://prnt.sc/Ann3srlQ1O9V

**Comment by JackMutobu** [comment]
@vishavsoftiatric can you check this issue again, login seems to be working fine from latest master branch? Or can we have more context?

**Comment by vishavsoftiatric** [comment]
@JackMutobu I have tested this issue on latest build and found this issue is still displaying and following are the credentials of the user is getting the error 
email - hanindo2000@yahoo.com 
licence key - QWPT-WZGI-KCLZ-0ECC

**Comment by JackMutobu** [comment]
@vishavsoftiatric this has been fixed in latest master build

**Comment by vishavsoftiatric** [comment]
@ezexe I have test this issue on latest build and found this issue is still displaying

**Comment by vishavsoftiatric** [comment]
@ezexe I have tested this issue on latest build ( 2025.0.2.6 ) and found issue is still displaying.

**Comment by vishavsoftiatric** [comment]
@ezexe I have tested this issue on latest build and found this issue is still displaying

**Comment by ezexe** [comment]
https://github.com/chameleonmode/chameleon.app-community/issues/69

**Comment by ezexe** [comment]
duplicate of?
https://github.com/chameleonmode/chameleon.app-community/issues/93

**Comment by vishavsoftiatric** [comment]
@ezexe I have tested this issue on latest build and found this issue is still displaying
**Bug recording**: https://drive.google.com/file/d/1jq84L8f8ZZAzShIfQaydg7fEqvwfI3BO/view?usp=drive_link
